services:
  server:
    image: vaultwarden/server:1.33.2
    restart: unless-stopped
    volumes:
      - /mnt/usb/egidio/docker/vaultwarden:/data
    networks:
      - web

networks:
  web:
    external: true
