name: home-server

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APACHE_PORT=${NEXTCLOUD_HTTP_PORT}
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/home/egidio/docker/nextcloud/ncdata
      - NEXTCLOUD_STARTUP_APPS=tasks calendar contacts notes
    ports:
      - 8080:8080

  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./vaultwarden:/data
    ports:
      - "${VAULTWARDEN_HTTP_PORT}:80"

  kitchenowl:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - FRONT_URL=https://kitchenowl.egidiocaprino.com
    volumes:
      - ./kitchenowl/data:/data
    env_file:
      - ./kitchenowl/.env

  kitchenowl-web:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    environment:
      - BACK_URL=kitchenowl:5000
    depends_on:
      - kitchenowl
    ports:
      - "${KITCHENOWL_HTTP_PORT}:80"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - "${TRANSMISSION_HTTP_PORT}:9091"
      - 51413:51413
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - USER=egidio
      - FILE__PASS=/run/secrets/password-secret.txt
      - HOST_WHITELIST=transmission.egidiocaprino.com
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
    secrets:
      - transmission-password

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./transmission/downloads/complete:/downloads:ro
    user: "${UID}:${GID}"
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.egidiocaprino.com
    ports:
      - "${JELLYFIN_HTTP_PORT}:8096"

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:latest
    volumes:
      - ./changedetection:/datastore
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      - BASE_URL=https://changedetection.egidiocaprino.com
      - USE_X_SETTINGS=1
      - HIDE_REFERER=false
      - FETCH_WORKERS=2
    ports:
      - "${CHANGE_DETECTION_HTTP_PORT}:5000"
    restart: unless-stopped

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.4.0
    restart: unless-stopped
    ports:
      - "${MEALIE_HTTP_PORT}:9000"
    volumes:
      - ./mealie:/app/data/
    environment:
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Europe/Rome
      BASE_URL: https://mealie.egidiocaprino.com

  paperless-redis:
    image: redis:7
    restart: unless-stopped

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-redis
    ports:
      - "${PAPERLESS_HTTP_PORT}:8000"
    volumes:
      - ./paperless/data:/usr/src/paperless/data
      - ./paperless/media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - ./paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      SERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGE: ita
      PAPERLESS_OCR_LANGUAGES: eng ita
      PAPERLESS_URL: https://paperless.egidiocaprino.com
      PAPERLESS_SECRET_KEY: fill-me
      PAPERLESS_TIME_ZONE: Europe/Rome

  portainer:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    ports:
      - "${PORTAINER_HTTP_PORT}:9000"
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

  grocy:
    image: lscr.io/linuxserver/grocy:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./config:/config
    ports:
      - "${GROCY_HTTP_PORT}:80"
    restart: unless-stopped

  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt/archive/egidiocaprino.com:/certs:ro
    depends_on:
      - nextcloud-aio-mastercontainer
      - vaultwarden
      - kitchenowl-web
      - transmission
      - changedetection
    network_mode: host
    environment:
      - NEXTCLOUD_HTTP_PORT=${NEXTCLOUD_HTTP_PORT}
      - VAULTWARDEN_HTTP_PORT=${VAULTWARDEN_HTTP_PORT}
      - KITCHENOWL_HTTP_PORT=${KITCHENOWL_HTTP_PORT}
      - TRANSMISSION_HTTP_PORT=${TRANSMISSION_HTTP_PORT}
      - JELLYFIN_HTTP_PORT=${JELLYFIN_HTTP_PORT}
      - CHANGE_DETECTION_HTTP_PORT=${CHANGE_DETECTION_HTTP_PORT}
      - MEALIE_HTTP_PORT=${MEALIE_HTTP_PORT}
      - PAPERLESS_HTTP_PORT=${PAPERLESS_HTTP_PORT}
      - PORTAINER_HTTP_PORT=${PORTAINER_HTTP_PORT}
      - GROCY_HTTP_PORT=${GROCY_HTTP_PORT}

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

secrets:
  transmission-password:
    file: ./transmission/password-secret.txt
