name: home-server

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - APACHE_PORT=${NEXTCLOUD_HTTP_PORT}
      - APACHE_IP_BINDING=0.0.0.0
      - NEXTCLOUD_DATADIR=/home/egidio/docker/nextcloud/ncdata
      - NEXTCLOUD_STARTUP_APPS=tasks calendar contacts notes
    ports:
      - 8080:8080

  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ./vaultwarden:/data
    ports:
      - "${VAULTWARDEN_HTTP_PORT}:80"

  kitchenowl:
    image: tombursch/kitchenowl:latest
    restart: unless-stopped
    environment:
      - JWT_SECRET_KEY=
      - FRONT_URL=https://kitchenowl.egidiocaprino.com
    volumes:
      - ./kitchenowl:/data

  kitchenowl-web:
    image: tombursch/kitchenowl-web:latest
    restart: unless-stopped
    environment:
      - BACK_URL=kitchenowl:5000
    depends_on:
      - kitchenowl
    ports:
      - "${KITCHENOWL_HTTP_PORT}:80"

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - "${TRANSMISSION_HTTP_PORT}:9091"
      - 51413:51413
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - USER=egidio
      - FILE__PASS=/run/secrets/password-secret.txt
      - HOST_WHITELIST=transmission.egidiocaprino.com
    volumes:
      - ./transmission/config:/config
      - ./transmission/downloads:/downloads
    secrets:
      - transmission-password

  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./transmission/downloads/complete:/downloads
    user: "${UID}:${GID}"
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.egidiocaprino.com
    ports:
      - "${JELLYFIN_HTTP_PORT}:8096"

  caddy:
    image: caddy:2
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt/archive/egidiocaprino.com:/certs
    depends_on:
      - nextcloud-aio-mastercontainer
      - vaultwarden
      - kitchenowl-web
      - transmission
    network_mode: host
    environment:
      - NEXTCLOUD_HTTP_PORT=${NEXTCLOUD_HTTP_PORT}
      - VAULTWARDEN_HTTP_PORT=${VAULTWARDEN_HTTP_PORT}
      - KITCHENOWL_HTTP_PORT=${KITCHENOWL_HTTP_PORT}
      - TRANSMISSION_HTTP_PORT=${TRANSMISSION_HTTP_PORT}
      - JELLYFIN_HTTP_PORT=${JELLYFIN_HTTP_PORT}

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

secrets:
  transmission-password:
    file: ./transmission/password-secret.txt
