services:
  server:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    image: lscr.io/linuxserver/grocy:latest
    networks:
      - web
    pull_policy: always
    restart: always
    volumes:
      - ./config:/config

networks:
  web:
    external: true
