apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: grocy
  name: grocy-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - grocy.egidiocaprino.com
    secretName: grocy-certificate
  rules:
  - host: grocy.egidiocaprino.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grocy-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: grocy
  name: grocy-service
spec:
  selector:
    app: grocy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: grocy
  name: grocy-config-volume-claim-2
  labels:
    app: grocy
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: grocy
  name: grocy-deployment
spec:
  selector:
    matchLabels:
      app: grocy
  template:
    metadata:
      labels:
        app: grocy
    spec:
      containers:
      - name: grocy
        image: linuxserver/grocy:3.3.2
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: Europe/Rome
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: grocy-config-volume-claim-2
