name: frp-server

services:
  frpc:
    image: gists/frp:0.61.0
    network_mode: host
    volumes:
      - ./frpc.toml:/etc/frpc.toml:ro
      - /etc/letsencrypt/archive/egidiocaprino.com/fullchain4.pem:/opt/fullchain.pem:ro
      - /etc/letsencrypt/archive/egidiocaprino.com/privkey4.pem:/opt/privkey.pem:ro
      - ./certificate.pem:/opt/frp/certificate.pem
      - ./private.key:/opt/frp/private.key
    command: frpc -c /etc/frpc.toml
    restart: always
