name: frp-server

services:
  frpc:
    image: gists/frp:0.61.0
    network_mode: host
    volumes:
      - ./frpc.toml:/etc/frpc.toml:ro
      - ./fullchain.pem:/opt/fullchain.pem:ro
      - ./privkey.pem:/opt/privkey.pem:ro
      - ./certificate.pem:/opt/frp/certificate.pem:ro
      - ./private.key:/opt/frp/private.key:ro
    command: frpc -c /etc/frpc.toml
    restart: always
