serverAddr = "3.75.235.221"
serverPort = 7000
transport.tls.enable = true
transport.tls.certFile = "/opt/frp/certificate.pem"
transport.tls.keyFile = "/opt/frp/private.key"

[[proxies]]
name = "home-server"
type = "https"
customDomains = ["*.egidiocaprino.com"]

[proxies.plugin]
type = "https2http"
localAddr = "127.0.0.1:80"
crtPath = "/opt/fullchain.pem"
keyPath = "/opt/privkey.pem"
