apiVersion: v1
kind: Namespace
metadata:
  name: kitchen-owl
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kitchen-owl
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - kitchen-owl.egidiocaprino.com
    secretName: kitchen-owl-certificate
  rules:
  - host: kitchen-owl.egidiocaprino.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kitchen-owl-web-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kitchen-owl
  name: kitchen-owl-web-service
spec:
  selector:
    app: kitchen-owl-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kitchen-owl
  name: kitchen-owl-backend-service
spec:
  selector:
    app: kitchen-owl-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kitchen-owl
  name: kitchen-owl-data-volume-claim
  labels:
    app: kitchen-owl-backend
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kitchen-owl
  name: kitchen-owl-web-deployment
spec:
  selector:
    matchLabels:
      app: kitchen-owl-web
  template:
    metadata:
      labels:
        app: kitchen-owl-web
    spec:
      containers:
      - name: kitchen-owl-web
        image: tombursch/kitchenowl-web
        ports:
        - containerPort: 80
        env:
        - name: BACK_URL
          value: kitchen-owl-backend-service:5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kitchen-owl
  name: kitchen-owl-backend-deployment
spec:
  selector:
    matchLabels:
      app: kitchen-owl-backend
  template:
    metadata:
      labels:
        app: kitchen-owl-backend
    spec:
      containers:
      - name: kitchen-owl-backend
        image: tombursch/kitchenowl
        ports:
        - containerPort: 5000
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret
              key: kitchen-owl-jwt-secret-key
        - name: FRONT_URL
          value: kitchen-owl.egidiocaprino.com
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kitchen-owl-data-volume-claim
