bindPort = 7000
vhostHTTPSPort = 443
webServer.addr = "0.0.0.0"
webServer.port = 7500
transport.tls.force = true
transport.tls.certFile = "/opt/frp/certificate.pem"
transport.tls.keyFile = "/opt/frp/private.key"
