apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: jellyfin
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - jellyfin.egidiocaprino.com
    secretName: jellyfin-certificate
  rules:
  - host: jellyfin.egidiocaprino.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin-service
            port:
              number: 8096
---
apiVersion: v1
kind: Service
metadata:
  namespace: jellyfin
  name: jellyfin-service
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jellyfin
  name: jellyfin-data-volume-claim
  labels:
    app: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: jellyfin-deployment
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        ports:
        - containerPort: 8096
        env:
        - name: JELLYFIN_PublishedServerUrl
          value: https://jellyfin.egidiocaprino.com
        - name: JELLYFIN_DATA_DIR
          value: /data
        volumeMounts:
        - name: data
          mountPath: /data
        - name: transmission
          mountPath: /transmission
        - name: music
          mountPath: /music
      volumes:
      - name: transmission
        hostPath:
          path: /mnt/transmission
      - name: data
        persistentVolumeClaim:
          claimName: jellyfin-data-volume-claim
      - name: music
        hostPath:
          path: /mnt/music
