apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: huginn
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: huginn.lenovo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: huginn-service
            port:
              number: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: huginn
  name: huginn-service
spec:
  selector:
    app: huginn
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: huginn
  name: huginn-mysql-volume-claim
  labels:
    app: huginn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: huginn
  name: huginn-deployment
spec:
  selector:
    matchLabels:
      app: huginn
  template:
    metadata:
      labels:
        app: huginn
    spec:
      initContainers:
      - name: alpine
        image: alpine:3.17.2
        command: ["/bin/sh", "-c", "/bin/chown -R 1001:0 /mnt"]
        volumeMounts:
        - name: mysql
          mountPath: /mnt
      containers:
      - name: huginn
        image: huginn/huginn:ba852f1edc26bf0e87d6a7a13389124e22d0bde0
        ports:
        - containerPort: 3000
        env:
        - name: DOMAIN
          value: huginn.lenovo.local
        - name: PORT
          value: "3000"
        - name: SMTP_USER_NAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: smtp-email
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: smtp-password
        - name: SMTP_SERVER
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_AUTHENTICATION
          value: plain
        - name: SMTP_ENABLE_STARTTLS_AUTO
          value: "true"
        - name: SMTP_SSL
          value: "false"
        - name: EMAIL_FROM_ADDRESS
          valueFrom:
            secretKeyRef:
              name: secret
              key: smtp-email
        - name: TIMEZONE
          value: Rome
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: huginn-mysql-volume-claim
