services:
  server:
    image: lscr.io/linuxserver/transmission:4.0.6-r2-ls280
    restart: unless-stopped
    ports:
      - 51413:51413
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - USER=home
      - FILE__PASS=/run/secrets/password-secret.txt
      - HOST_WHITELIST=transmission.egidiocaprino.com
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    secrets:
      - transmission-password
    networks:
      - web

networks:
  web:
    external: true

secrets:
  transmission-password:
    file: ./password-secret.txt
