apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: transmission
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: transmission.lenovo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: transmission-ui-service
            port:
              number: 9091
---
apiVersion: v1
kind: Service
metadata:
  namespace: transmission
  name: transmission-ui-service
spec:
  selector:
    app: transmission
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  namespace: transmission
  name: transmission-peer-service
spec:
  type: LoadBalancer
  selector:
    app: transmission
  ports:
  - protocol: TCP
    port: 51413
    targetPort: 51413
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: transmission
  name: transmission-download-volume-claim
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: transmission
  name: transmission-deployment
spec:
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: lscr.io/linuxserver/transmission:4.0.1
        ports:
        - containerPort: 9091
        - containerPort: 51413
        env:
        - name: TZ
          value: Europe/Rome
        - name: USER
          value: egidio
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: secret
              key: egidio-password
        - name: PEERPORT
          value: "51413"
        volumeMounts:
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: transmission-download-volume-claim
